<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="stylesheet/stylesheet.css">
    <title>Sushi</title>
</head>

<body>
<nav>
    <li><a href="home">Home</a></li>
    <li><a href="HotPot.php">Hot Pot</a></li>
    <li><a href="Sushi.php">Sushi</a></li>
    <li><a href="InstantNoodles.php">Noodles</a></li>
    <li><a href="#bestellen">Bestellen</a></li>
</nav>
    <div class="container">
        <div class="group-header">
            <span>12 oz.</span>
            <span>34 oz.</span>
        </div>

        <h3>
            <span>California Roll<img class="img" src="./Images/Cali.jpg" alt="CaliRoll"></span>
            <span>25$ for 10Rolls</span>
            <span>------</span>
            <span> 30$ for 15Rolls</span>
            <span>----</span>
            <button>Order</button>
        </h3>
        <p>A California roll is usually made with crab and avocado. If you purchase a California roll in a supermarket,
            you may get one with mayonnaise in it. In the California roll above, there is crab, ahi (tuna), and avocado.
            Sometimes it will be served with a slab of ahi on top.</p>
        <h3>
            <span>Tempura Roll <img class="img" src="./Images/Roll1.jpg" alt="TempRoll"></span>
            <span>15$ for 8Rolls</span>
            <span>------</span>
            <span> 4$ for 16Rolls</span>
            <span>----</span>
            <button>Order</button>
        </h3>
        <p>Tempura is a Japanese style of deep frying that uses a light batter. As shown in the photo above, one way to
            make this crunchy delight is to make the entire roll tempura. In the photo above, the chef created sashimi
            rolls, covered it in tempura batter, and deep-fried the whole thing.</p>
        <h3>
            <span>Philly Roll<img class="img" src="./Images/Philly.jpg" alt="PhillyRoll"></span>
            <span>12$ for 5Rolls</span>
            <span>------</span>
            <span> 17$ for 10Rolls</span>
            <span>----</span>
            <button>Order</button>
        </h3>
        <p>The Philly roll is a popular kind of sushi that you will find on many menus around the country. It usually
            has salmon, cream cheese, and cucumber, though it might come with other ingredients like avocado, onion, and
            sesame seed. It's named the Philly roll because of Philadelphia Cream Cheese, not because it's from
            Philadelphia.</p>
        <h3>
            <span>Inari<img class="img" src="./Images/Inari.jpg"></span>
            <span>16$ for 10Rolls</span>
            <span>------</span>
            <span>25$ for 20Rolls</span>
            <span>----</span>
            <button>Order</button>
        </h3>
        <p>Inari is breaded-rice sushi. The bread is thin and sweet and sometimes filled with vegetables such as carrot
            strips or cucumber. Recommended for a light snack</p>
        <h3>
            <span>Rainbow Roll <img class="img" src="./Images/RainbowR.jpg"></span>
            <span>23$ for 15Rolls</span>
            <span>------</span>
            <span>32$ for 24Rolls</span>
            <span>----</span>
            <button>Order</button>
        </h3>
        <p>A rainbow roll is a sushi roll topped with many different types of sashimi.
            The sushi roll underneath the sashimi is usually a California roll (avocado and crab).
            To make this type of sushi, the chef prepares a California roll and adds the toppings afterwards.</p>
    </div>
</body>

</html>